apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-redis
  template:
    metadata:
      labels:
        app: argocd-redis
    spec:
      imagePullSecrets:
      - name: dockerhub-credentials
      containers:
      - name: redis
        image: redis:7.0.15-alpine
